type: "transformation"
version: "1.0"
pipeline:
  components:
    FLIGHTS_DATA:
      type: "table-input"
      parameters:
        componentName: "FLIGHTS_DATA"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "FLIGHTS_DATA"
        columnNames:
        - "ID"
        - "YEAR"
        - "MONTH"
        - "DAY"
        - "DEP_TIME"
        - "SCHED_DEP_TIME"
        - "DEP_DELAY"
        - "ARR_TIME"
        - "SCHED_ARR_TIME"
        - "ARR_DELAY"
        - "CARRIER"
        - "FLIGHT"
        - "TAILNUM"
        - "ORIGIN"
        - "DEST"
        - "AIR_TIME"
        - "DISTANCE"
        - "HOUR"
        - "MINUTE"
        - "TIME_HOUR"
        - "NAME"
        timeOffset:
    id_not_null:
      type: "filter"
      sources:
      - "FLIGHTS_DATA"
      parameters:
        componentName: "id_not_null"
        filterConditions:
        - - "ID"
          - "Not"
          - "Null"
          - ""
        combineCondition: "And"
    null_id:
      type: "filter"
      sources:
      - "FLIGHTS_DATA"
      parameters:
        componentName: "null_id"
        filterConditions:
        - - "ID"
          - "Is"
          - "Null"
          - ""
        combineCondition: "And"
    Rank:
      type: "rank"
      sources:
      - "id_not_null"
      parameters:
        componentName: "Rank"
        includeInputColumns: "Yes"
        partitionData:
        orderingWithinPartitions:
        - - "TIME_HOUR"
          - "Ascending"
        functions:
        - - "Row Number"
          - "rank"
    rank_is_1:
      type: "filter"
      sources:
      - "Rank"
      parameters:
        componentName: "rank_is_1"
        filterConditions:
        - - "rank"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
    FLIGHTS_DATA_FILTERED:
      type: "table-output"
      sources:
      - "rank_is_1"
      parameters:
        componentName: "FLIGHTS_DATA_FILTERED"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "FLIGHTS_DATA_FILTERED"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "ID"
          - "ID"
        - - "YEAR"
          - "YEAR"
        - - "MONTH"
          - "MONTH"
        - - "DAY"
          - "DAY"
        - - "DEP_TIME"
          - "DEP_TIME"
        - - "SCHED_DEP_TIME"
          - "SCHED_DEP_TIME"
        - - "DEP_DELAY"
          - "DEP_DELAY"
        - - "ARR_TIME"
          - "ARR_TIME"
        - - "SCHED_ARR_TIME"
          - "SCHED_ARR_TIME"
        - - "ARR_DELAY"
          - "ARR_DELAY"
        - - "CARRIER"
          - "CARRIER"
        - - "FLIGHT"
          - "FLIGHT"
        - - "TAILNUM"
          - "TAILNUM"
        - - "ORIGIN"
          - "ORIGIN"
        - - "DEST"
          - "DEST"
        - - "AIR_TIME"
          - "AIR_TIME"
        - - "DISTANCE"
          - "DISTANCE"
        - - "HOUR"
          - "HOUR"
        - - "MINUTE"
          - "MINUTE"
        - - "TIME_HOUR"
          - "TIME_HOUR"
        - - "NAME"
          - "NAME"
        - - "rank"
          - "ROW_NUM"
        orderBy:
        outputMode: "Append"
    rank>1:
      type: "filter"
      sources:
      - "Rank"
      parameters:
        componentName: "rank>1"
        filterConditions:
        - - "rank"
          - "Is"
          - "Greater than"
          - "1"
        combineCondition: "And"
    Unite:
      type: "unite"
      sources:
      - "null_id"
      - "rank>1"
      parameters:
        componentName: "Unite"
        method: "All Columns"
        castTypes: "Yes"
        addSourceComponentColumn: "No"
        removeDuplicates: "No"
    Problamatic_data:
      type: "table-output"
      sources:
      - "Unite"
      parameters:
        componentName: "Problamatic_data"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "PROBLEMATIC_FLIGHTS_DATA"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "ID"
          - "ID"
        - - "YEAR"
          - "YEAR"
        - - "MONTH"
          - "MONTH"
        - - "DAY"
          - "DAY"
        - - "DEP_TIME"
          - "DEP_TIME"
        - - "SCHED_DEP_TIME"
          - "SCHED_DEP_TIME"
        - - "DEP_DELAY"
          - "DEP_DELAY"
        - - "ARR_TIME"
          - "ARR_TIME"
        - - "SCHED_ARR_TIME"
          - "SCHED_ARR_TIME"
        - - "ARR_DELAY"
          - "ARR_DELAY"
        - - "CARRIER"
          - "CARRIER"
        - - "FLIGHT"
          - "FLIGHT"
        - - "TAILNUM"
          - "TAILNUM"
        - - "ORIGIN"
          - "ORIGIN"
        - - "DEST"
          - "DEST"
        - - "AIR_TIME"
          - "AIR_TIME"
        - - "DISTANCE"
          - "DISTANCE"
        - - "HOUR"
          - "HOUR"
        - - "MINUTE"
          - "MINUTE"
        - - "TIME_HOUR"
          - "TIME_HOUR"
        - - "NAME"
          - "NAME"
        - - "rank"
          - "ROW_NUM"
        orderBy:
        outputMode: "Append"
design:
  components:
    FLIGHTS_DATA:
      position:
        x: -210
        "y": -40
      tempMetlId: 1
    id_not_null:
      position:
        x: -80
        "y": -90
      tempMetlId: 2
    null_id:
      position:
        x: 120
        "y": 120
      tempMetlId: 3
    Rank:
      position:
        x: 40
        "y": -90
      tempMetlId: 4
    rank_is_1:
      position:
        x: 160
        "y": -90
      tempMetlId: 5
    FLIGHTS_DATA_FILTERED:
      position:
        x: 280
        "y": -90
      tempMetlId: 6
    rank>1:
      position:
        x: 120
        "y": 20
      tempMetlId: 7
    Unite:
      position:
        x: 240
        "y": 90
      tempMetlId: 8
    Problamatic_data:
      position:
        x: 360
        "y": 90
      tempMetlId: 9
